---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mimeograph
  namespace: mimeograph
  labels:
    app.kubernetes.io/name: mimeograph
    app.kubernetes.io/part-of: mimeograph
subjects:
  - kind: ServiceAccount
    name: mimeograph
    namespace: mimeograph
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:anyuid'