== Mimeograph

Noun: A duplicating machine which produces copies from a stencil.

Mimeograph is a simple script to enable the copying of container images from one source container registry (such as docker.io) to another target container registry. Under the covers, it leverages link:https://stedolan.github.io/jq[JQ] to parse JSON metadata from the source repository, and link:https://github.com/containers/skopeo[Skopeo] to copy the container image and any associated tags. The only addition above and beyond what Skopeo provides, is simply in the ability to read in a file of containers to copy and itterate over them. Like I said, simple. Useful for syncing containers between repositories in differing environments.

It was originally heavily targeted towards OpenShift and the Atomic Enterprise Registry (because thats what I mainly and still often use), but has been extended somewhat to reliably target Quay. Other repositories ought to be easy to integrate.   

If honest, I should have done it in Python from the start, so will probably port it to that at some stage. Or maybe Go, since Skopeo uses that.

=== Usage
As it's a simple BASH script, you can simply clone this repo and run it directly from the terminal. There is also a Dockerfile too if thats how you want to run it. The Dockerfile leverages the lightweight rhel-atomic image, but should be easy to adapt to whatever you find easiest.

All config is held in the `config.json` file. It's pretty simple, simply define your Upstream and Target repositories, and provide a list of container images you want to copy ordered into projects/namespaces.  

.Command Line
`$ ./mimeograph.sh`

.Docker

OPTIONAL: If you want to embed a sane config.json file within the docker image, Copy/Edit config.json.sample to config.json, and set with your requirements.

Build the image...
`$ docker build -t mimeograph .`

Run the image...
`$ docker run -it -v ${PWD}/config.json:/config.json mimeograph`


=== OpenShift

TODO: How to run in OCP.


=== Limitations

Am sure there are loads, but OTTOMH.

* I wrote it.
* Currently it retrieves *all* tags for *every* image defined, which can mean a hefty download for poorly organised, or rapidly released container images. Be good to limit this somewhat.
* The namespacing is a bit loose, and am sure will cause headaches.
* I've done no testing for edge-cases. To be honest, I've done very little testing at all.


=== TODO

(If I get time or am motivated)

* Make more generic to support other registry types
* Port to Python/Go



