apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
archiveSize: 4
mirror:
  platform:
    architectures:
      - "amd64"
    channels:
      - name: stable-4.11
        minVersion: '4.11.5'
        maxVersion: '4.11.9'
      - name: stable-4.10
        minVersion: '4.10.30'
        maxVersion: '4.10.35'
    graph: true
storageConfig:
  local:
    path: /mimeograph/metadata