apiVersion: mimeograph.io/v1alpha1
kind: MimeographConfiguration
operation: bundle
mirror:
  imagesetConfig: /mimeograph/mimeograph-imageset.yaml
  targetRegistryURI: disconnected.registry.example.com/mimeograph
s3:
  bucket:
    name: mimeograph-bucket
    endpoint: https://s3-openshift-storage.apps.ocp.example.com/
    subDir: container-images
artefacts:
  bundleDir: /mimeograph/bundle
  metadataDir: /mimeograph/metadata